# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
avatar:           https://avatars1.githubusercontent.com/u/44785839?s=400&u=7736abb34f4b291aadaeda36b33247fe388fc8e7&v=4
title:            Andrew Avalos
tagline:          'A Jekyll theme'
description:      Aspiring Data Scientist
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Andrew Avalos'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
