# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
avatar:           https://avatars1.githubusercontent.com/u/44785839?s=400&u=7736abb34f4b291aadaeda36b33247fe388fc8e7&v=4
title:            Andrew Avalos
description:      Aspiring Data Scientist
url:              https://github.com/acavalos/acavalos.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0
